ToDoList/Controllers/ListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using ToDoList.Models;


namespace ToDoList.Controllers
{
    public class ListController : Controller
    {

        private readonly DBContext _context;

        public ListController(DBContext c)
        {
            _context = c;
        }


        [HttpGet]
        public async Task<IActionResult> ListToday(bool showCompleted = false)
        {
        
            List<UserTask> tasks;
            if (showCompleted)
            {
                tasks = await _context.userTask.Where(z => z.TaskDone != null
                && z.LoginUser.LoginUser == User.Identity.Name).ToListAsync(); 
            }
            else
            {
                tasks = await _context.userTask.Where(z => z.TaskDone == null
                && z.LoginUser.LoginUser == User.Identity.Name).ToListAsync();
            }
            return View(tasks);
        }


        public async Task<IActionResult> ListCome(string dateString = null, bool showCompleted = false)
        {
            DateTime dateTime = DateTime.UtcNow;

            var lc = new ListComeModel();

            if (!string.IsNullOrEmpty(dateString))
            {
                DateTime.TryParse(dateString, System.Globalization.CultureInfo.InvariantCulture,
                System.Globalization.DateTimeStyles.AssumeUniversal, out dateTime);
            }

            dateTime = dateTime.Date;

            lc.Date = dateTime.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            lc.MonthDate = dateTime.ToString("MMMM yyyy", CultureInfo.InvariantCulture);

            List<DateTime> days = new List<DateTime>();
            for (var x = 0; x <= 7; x++)
            {
                var day = dateTime.AddDays(x);
               
                days.Add( day.Date);
            }
            lc.Days = days;

            List<UserTask> tasks;
            if (showCompleted)
            {
                tasks = await _context.userTask.Where(z => z.TaskDone != null
                && z.LoginUser.LoginUser == User.Identity.Name
                && z.TaskCreate >= dateTime && z.TaskCreate <= dateTime.AddDays(7)).ToListAsync();
            }
            else
            {
                tasks = await _context.userTask.Where(z => z.TaskDone == null
                && z.LoginUser.LoginUser == User.Identity.Name
                && z.TaskCreate >= dateTime && z.TaskCreate <= dateTime.AddDays(7)).ToListAsync();
            }
            lc.Tasks = tasks.GroupBy(z => z.TaskCreate.Date)
            .ToDictionary(z => z.Key, z => z.ToList());

            foreach (var d in lc.Days)
            {
               if(!lc.Tasks.ContainsKey(d))
                { 
                    lc.Tasks.Add(d, new());
                }
               

               
            }
            return View(lc);
        }


    
        [HttpPost]
        public async Task<IActionResult> SaveTask(TaskModel model)
        {
            var user = _context.userInfo.First(z => z.LoginUser == User.Identity.Name);
            _context.userTask.Add(new UserTask()
            {
                LoginUser = user,
                Taskk = model.Taskk,
                TaskCreate = model.Create
            });

            await _context.SaveChangesAsync();
            return RedirectToAction(model.ActionName);
        }


        [HttpPost]
        public async Task<IActionResult> CloseTask(int id, ListComeModel model)
        {
            var res = await _context.userTask.FirstOrDefaultAsync(z => z.Id == id);
            if (res != null)
            {
                res.TaskDone = DateTime.UtcNow;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(model.ActionName);
        }



        [HttpPost]
        public async Task<IActionResult> DeleteTask(int id, ListComeModel model)
        {
            var res = await _context.userTask.FirstOrDefaultAsync(z => z.Id == id);
            if (res != null)
            {

                _context.userTask.Remove(res);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(model.ActionName);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeTask(ChangeTaskModel model)
        {
            var res = await _context.userTask.FirstOrDefaultAsync(z => z.Id == model.Id);
            if (res != null)
            {
       
               res.Taskk = model.Text;
           
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(model.ActionName);
        }

    }
}

ToDoList/Views/List/ListCome.cshtml
@model ToDoList.Models.ListComeModel
@using ToDoList

@{
    ViewData["Title"] = "index";
    Layout = "_Layout1";


}
@section CssAndScript1 {
<link href="~/css/come.css" rel="stylesheet" />
<link href="~/css/task.css" rel="stylesheet" />
<link href="~/jquery/jquery-ui.css" rel="stylesheet" />

<script src="~/jquery/jquery.js"></script>
<script src="~/jquery/jquery-ui.js"></script>
}

<div class="rightSide">
    <form action="ListCome" method="get" id="form1">
        <div id="dpcontainer" class="ui-widget">

            <input id="datep" type="hidden" name="dateString" />
            <div id="monthDate">
                @Model.MonthDate<div id="monthImg">
                    <svg width="24" height="25" xmlns="http://www.w3.org/2000/svg" stroke="null">
                        <g id="Layer_1">
                            <title>Layer 1</title>
                            <path transform="rotate(89.4146 11.753 15.2635)" stroke="#000" id="svg_1" d="m12.16699,15.26348l-2.42499,-4.5l1.59705,0l2.42499,4.5l-2.42499,4.5l-1.59705,0l2.42499,-4.5z" fill="#4c4c4c" />
                        </g>

                    </svg>
                </div>
            </div>
        </div>
    </form>

    <div class="DaysHolder">

        @foreach (var d in Model.Days)
        {

            <div class="days">
                <a class="daysA mon" href="@Model.DayToURI(Url,d)">
                    @Model.DateToDayName(d)
                </a><a class="daysA" href="@Model.DayToURI(Url,d)">
                    @Model.DateToMonthDate(d)
                </a>
            </div>
        }
    </div>
   
    @foreach (var entry in Model.Tasks.OrderBy(z => z.Key.Date))
    {
        <div class="come">
            <div class="dayToList">@Model.DateForList(entry.Key) </div>
            <div class="line"></div>

            @foreach (var task in entry.Value)
            {
                <div><partial name="_task" model="@task" /> </div>
            }


            <div>
                <partial name="_AddTask" model="@entry.Key.Date" />
            </div>

        </div>
    }
    <div class="linee"></div>
 
</div>











<script type="text/javascript">
    $(() => {

        $.datepicker.setDefaults($.datepicker.regional['ru']);
        $('#datep').datepicker({
             range: 'period',
            changeMonth: true,
            changeYear: true,
            yearRange: ":+5",
            minDate: "0",
            constrainInput: true,

        }).datepicker("setDate", "@Model.Date");

        $("#datep").change(() => {
            $("#form1").submit();
        });

        $("#monthDate").click((e) => {
            $('#datep').datepicker("show");
        });


        $(".disFlex2").click((e) => {
            $(".disFlex2",$(e.target).parents(".addParent")).css("display","none");
            $(".boxInput",$(e.target).parents(".addParent")).css("display","block");
        });


        $("#btn2").click((e) => {
            $(".disFlex2",e.target.parentElement).css("display","flex");
            $(".boxInput",e.target.parentElement).css("display","none");
        });



         $(".checkg").mouseenter((e) => {
            $(".CloseButtonColor", e.target.parentElement).css("fill", "#cbced4");
            $(".markk", e.target.parentElement).css("fill", "#696b6e");
            $(".markk", e.target.parentElement).css("stroke", "#696b6e");
        });

        $(".checkg").mouseleave((e) => {
            $(".CloseButtonColor", e.target.parentElement).css("fill", "white");
            $(".markk", e.target.parentElement).css("fill", "white");
            $(".markk", e.target.parentElement).css("stroke", "white");
        });
                $(".disFlex2").mouseenter((e) => {
               $("#plus",e.target.parentElement).addClass("plusC");
               $("#task",e.target.parentElement).addClass("taskC");
        });

        $(".disFlex2").mouseleave((e) => {
               $("#plus",e.target.parentElement).removeClass("plusC");
               $("#task",e.target.parentElement).removeClass("taskC");
        });

        $(".clickk").click((e) => {
            $(e.target).parents("form").attr("action", "@Url.Action("CloseTask", "List")");
            $(e.target).parents("form").submit();
        });

        $(".clickDel").click((e)=>{

                 $(e.target).parents("form").attr("action", "@Url.Action("DeleteTask", "List")");
                 $(e.target).parents("form").submit();
        });

       $(".saveTask").click((e)=>{
                 $(e.target).parents("form").attr("action", "@Url.Action("ChangeTask", "List")");
                 $(e.target).parents("form").submit();
            e.preventDefault();
        });

          $(".clickChange").click((e)=>{
            $(".taskdisplayreadonly",$(e.target).parents(".taskEach")).css("display","none");
            $(".taskEdit",$(e.target).parents(".taskEach")).css("display","block");
        });

        $(".cancelTask").click((e)=>{
             $(".taskdisplayreadonly",$(e.target).parents(".taskEach")).css("display","flex");
            $(".taskEdit",$(e.target).parents(".taskEach")).css("display","none");
            e.preventDefault();

        });


    });




</script>

ToDoList/Views/List/ListToday.cshtml
@using ToDoList
@model List<UserTask>
@{
    ViewData["Title"] = "index";
    Layout = "_Layout1";


}
@section CssAndScript1 {
<link href="~/css/today.css" rel="stylesheet" />
<link href="~/css/task.css" rel="stylesheet" />
<link href="~/jquery/jquery-ui.css" rel="stylesheet" />

<script src="~/jquery/jquery.js"></script>
<script src="~/jquery/jquery-ui.js"></script>
}




<div class="rightSide">
    <div class="disFlex1"><div id="today">Today </div><div id="dateToday">@DateTime.Now.ToString("ddd d MMM  ", System.Globalization.CultureInfo.GetCultureInfoByIetfLanguageTag("en-us"))</div></div>


    @foreach (var task in Model)
    {
      
        <div><partial name="_task" model="@task" /> </div>
    }

    <partial name="_AddTask" model="@DateTime.Now.Date" />


</div>


<script>
    $(() => {
       $(".disFlex2").click((e) => {
            $(".disFlex2",$(e.target).parents(".addParent")).css("display","none");
            $(".boxInput",$(e.target).parents(".addParent")).css("display","block");
        });


        $("#btn2").click((e) => {
            $(".disFlex2",$(e.target).parents(".addParent")).css("display","flex");
            $(".boxInput",$(e.target).parents(".addParent")).css("display","none");
            e.preventDefault(); 
        });



         $(".checkg").mouseenter((e) => {
            $(".CloseButtonColor", e.target.parentElement).css("fill", "#cbced4");
            $(".markk", e.target.parentElement).css("fill", "#696b6e");
            $(".markk", e.target.parentElement).css("stroke", "#696b6e");
        });

        $(".checkg").mouseleave((e) => {
            $(".CloseButtonColor", e.target.parentElement).css("fill", "white");
            $(".markk", e.target.parentElement).css("fill", "white");
            $(".markk", e.target.parentElement).css("stroke", "white");
        });
                $(".disFlex2").mouseenter((e) => {
               $("#plus",e.target.parentElement).addClass("plusC");
               $("#task",e.target.parentElement).addClass("taskC");
        });

        $(".disFlex2").mouseleave((e) => {
               $("#plus",e.target.parentElement).removeClass("plusC");
               $("#task",e.target.parentElement).removeClass("taskC");
        });

        $(".clickk").click((e) => {
            $(e.target).parents("form").attr("action", "@Url.Action("CloseTask", "List")");
            $(e.target).parents("form").submit();
        });

        $(".clickDel").click((e)=>{

                 $(e.target).parents("form").attr("action", "@Url.Action("DeleteTask", "List")");
                 $(e.target).parents("form").submit();
        });
 
        $(".saveTask").click((e)=>{
                 $(e.target).parents("form").attr("action", "@Url.Action("ChangeTask", "List")");
                 $(e.target).parents("form").submit();
            e.preventDefault();
        });

          $(".clickChange").click((e)=>{
            $(".taskdisplayreadonly",$(e.target).parents(".taskEach")).css("display","none");
            $(".taskEdit",$(e.target).parents(".taskEach")).css("display","block");
        });

        $(".cancelTask").click((e)=>{
             $(".taskdisplayreadonly",$(e.target).parents(".taskEach")).css("display","block");
            $(".taskEdit",$(e.target).parents(".taskEach")).css("display","none");
            e.preventDefault();

        });


    });
</script>